# Generated by Django 6.0.3 on 2026-03-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
                ("description", models.TextField()),
                ("full_description", models.TextField()),
                (
                    "price_standard",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("delivery_standard", models.IntegerField(blank=True, null=True)),
                ("revisions_standard", models.IntegerField(blank=True, null=True)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/main/"
                    ),
                ),
                ("image_vector", models.JSONField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("orders_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
