# Generated by Django 6.0.3 on 2026-03-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_active'),
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='products.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.projectboard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
