# Generated by Django 6.0.3 on 2026-03-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_feedback_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_file',
            field=models.FileField(blank=True, null=True, upload_to='deliveries/'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
