# Generated by Django 6.0.3 on 2026-03-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_vector',
        ),
    ]
